num1=float(input("enter the first number: "))
num2=float(input("enter the second number: "))
print("addition",num1+num2)
print("subtraction",num1-num2)
print("multiplication",num1*num2)
print("division",num1/num2)